### PR TITLE
readme to tic

### PR DESCRIPTION
**Pull request by XP3691**
turned Readme file into tic project

### CODE REVIEW

**Comment by XP3691** [comment]
@MikiPonsy1

**Comment by MikiPonsy1** [comment]
[https://suspicious-kirch-ac96d7.netlify.app/](url)

**Comment by MikiPonsy1** [comment]
[description1-changes.zip](https://github.com/XP3691/Tristan-/files/5290601/description1-changes.zip)

**Comment by MikiPonsy1** [comment]
[TIC.zip](https://github.com/XP3691/Tristan-/files/5290612/TIC.zip)

**Pull request merged**
